---
#
# This playbook is a Debian Linux only playground playbook for GAWDS (c)2017
#
- name: Ping 
  hosts: piww

  tasks:
  - name: ping
    ping:

- name: Date
  hosts: piww

  tasks:
  - shell: /bin/date

- name: Update Packages on all PiWW Hosts
  hosts: piww

  tasks:
  - apt: 
     update_cache: yes

#  - apt: 
#    name: "*"
#    state: present

#  - apt:
#     upgrade: yes

  - apt:
     upgrade: dist

#- name: AutoRemove
#  hosts: piww
#  
#  tasks:
#  - name: AutoRemove 
#     command: apt-get -y autoremove
#     register: autoremove_output
#     changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
#
#- name: Autoremove unused packages
#      autoremove: yes

