---
# windows-updates.yml

- hosts: db
  serial: 1
  remote_user: user@DOMAIN.COM

  tasks:

    # Check of there are missing updates
      - block:
          - name: Check for missing updates.
            win_updates: state=searched
            register: update_count
          - name: List missing updates
            debug: var=update_count
